kiplot:
  version: 1

global:
  solder_mask_color: blue
  pcb_finish: ENIG

filters:
  - name: all_smd
    type: generic
    exclude_smd: true
    invert: true

  - name: all_front
    type: generic
    exclude_bottom: true

  - name: all_back
    type: generic
    exclude_top: true

  - name: all_tht
    type: generic
    exclude_tht: true
    invert: true

  - name: all_conn
    type: generic
    exclude_any:
      - field: Value
        regex: '.*CONN.*'
      - field: Value
        regex: 'SERVO.*'
      - field: Reference
        regex: 'JP.*'
      - field: Reference
        regex: 'U.*'
    invert: true

outputs:
  - name: PcbDraw
    comment: "How to draw a step"
    type: pcbdraw
    run_by_default: false
    options:
      format: png

  - name: KiCad_3D
    comment: "How to draw a step"
    type: render_3d
    run_by_default: false
    options:
      width: 1280
      height: 960
      orthographic: true
      zoom: 4
      ray_tracing: true
      background1: "#DAF1FF"
      auto_crop: true
      # transparent_background: true
      # transparent_background_color: "#00FF00"
      # transparent_background_fuzz: 15

  - name: Populate3D
    comment: "Populate example using KiCad render"
    type: populate
    dir: Render_3D
    options:
      renderer: KiCad_3D
      input: configs/with_filter_html.md

  - name: Populate2D
    comment: "Populate example using PcbDraw"
    type: populate
    dir: PcbDraw
    options:
      renderer: PcbDraw
      input: configs/with_filter_html.md
