name: "Populate example"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'
      - '.github/workflows/populate.yml'
  pull_request:
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'
      - '.github/workflows/populate.yml'
  repository_dispatch:
    types: [run_pop]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  populate:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad6_auto_full:dev

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Populate 2D
      run: |
        kibot -c configs/populate_with_filter.kibot.yaml -b PCBs/Ardu/ArduinoLearningKitStarter.kicad_pcb -d Generated Populate2D

    - name: Populate 3D
      run: |
        kibot -c configs/populate_with_filter.kibot.yaml -b PCBs/Ardu/ArduinoLearningKitStarter.kicad_pcb -d Generated Populate3D

    - name: Populate HQ
      run: |
        kibot -c configs/populate_with_filter.kibot.yaml -b PCBs/Ardu/ArduinoLearningKitStarter.kicad_pcb -d Generated PopulateHQ

    - name: Retrieve results
      uses: actions/upload-artifact@v3
      with:
        name: Generated_example
        path: Generated

  # This step is to upload the results to another repo (web pages)
  deploy:
    runs-on: ubuntu-latest
    needs: populate

    steps:
    - uses: actions/checkout@v3

    - name: Retrieve results
      uses: actions/download-artifact@v3
      with:
        name: Generated_example
        path: Generated

    - name: Deploy navigate results
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: Generated
        branch: main
        clean: false
        target-folder: Generated
